export default {
    "all": "All",
    "arts": "Arts and Entertainment",
    "business-and-finance": "Business and Finance",
    "creative-works": "Creative Works",
    "education": "Education",
    "events": "Events",
    "food-and-dining": "Food and Dining",
    "government-and-civic": "Government and Civic",
    "health-and-medical": "Health and Medical",
    "jobs-and-employment": "Jobs and Employment",
    "legal": "Legal",
    "local-business": "Local Business",
    "media-and-news": "Media and News",
    "order": "Order",
    "organizations": "Organizations",
    "people": "People",
    "places": "Places",
    "products-and-services": "Products and Services",
    "real-estate": "Real Estate",
    "retail-and-commerce": "Retail and Commerce",
    "reviews-and-ratings": "Reviews and Ratings",
    "science-and-nature": "Science and Nature",
    "social-and-cultural": "Social and Cultural",
    "sports": "Sports",
    "technology-and-computing": "Technology and Computing",
    "tourism": "Tourism",
    "transportation": "Transportation",
    "webpage": "Web Page",
    "website": "Web Site",
    "miscellaneous": "Miscellaneous",
}
